### ISSUE TITLE
opening Load order.md opens dynamic block files and dynamic-block.md opens Load order files in the Video-Document Mapper

### ISSUE THREAD

**Issue by pranjal779** [zealvora/terraform-beginner-to-advanced-resource#40]
when clicking on 27 | Load Order and Semantics -> dynamic block code opens up
and when clicking 28 | Dynamic Blocks -> load order code opens up
but if I select the files at the left side bar they open correct files.

https://github.com/zealvora/terraform-beginner-to-advanced-resource/assets/50409572/a9134107-21d0-47ba-854e-a6915e3a596c

**Comment by zealvora** [comment]
Thanks for reporting the issue. It has now been fixed.
