### ISSUE TITLE
graph.tf has deprecated element

### ISSUE THREAD

**Issue by pranjal779** [zealvora/terraform-beginner-to-advanced-resource#41]
resource "aws_eip" "lb" {
  instance = aws_instance.myec2.id
  vpc      = true
}

you get this message:
"vpc" is deprecated

removing vpc = true or commenting it, removed the message

**Comment by zealvora** [comment]
Hi Pranjal

Thanks for reporting the issue. We have removed the older video and new video for "Terraform Graph" is now available in the course. This should fix the issue.
