### ISSUE TITLE
cannot see the varification badge in the Terraform Registry lesson in the Terraform Module & Workspaces Section

### ISSUE THREAD

**Issue by pranjal779** [zealvora/terraform-beginner-to-advanced-resource#42]
![image](https://github.com/zealvora/terraform-beginner-to-advanced-resource/assets/50409572/5d24a570-77c0-4597-abcf-dfca3c6bf012)

**Comment by zealvora** [comment]
Hi Pranjal

Thanks for pointing this out.

The Terraform Registry lecture has been removed as part of our previous update, and we have a new set of videos available for the section "Terraform Modules."

The newer set of videos discusses the latest changes to the Terraform Registry.

**Comment by pranjal779** [comment]
Thank you @zealvora
