### ISSUE TITLE
Suggestion to code update? reource "aws_eip" in the eip.tf file in lesson 111 Implementing Remote State Connections

### ISSUE THREAD

**Issue by pranjal779** [zealvora/terraform-beginner-to-advanced-resource#43]
original code:
```hcl
resource "aws_eip" "lb" {
  vpc      = true
}
```
here vpc = ture is deprecated

the code i replaced it with after reading the doc:
```hcl
resource "aws_eip" "lb" {
  # vpc = true -> is deprecated
  domain = "vpc"
}
```

**Comment by pranjal779** [comment]
[vpc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip#vpc) - (Optional Deprecated) Boolean if the EIP is in a VPC or not. Use domain instead. Defaults to true unless the region supports EC2-Classic.

[domain](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip#domain) - Indicates if this EIP is for use in VPC (vpc).

**Comment by zealvora** [comment]
Thanks for sharing the details. Although most of the videos where the older format of EIP was used were updated, the remote state practical video has not yet been updated and we are working on it. 

Meanwhile, we have updated the aws_eip resource to use domain = "vpc", so it does not create issues with the latest version of Terraform and Plugins.

**Comment by pranjal779** [comment]
Thank you @zealvora
